colorscheme: white

nav:
  home: /
  tag: /tags/
  articles: /archives/
  about: /about/

posts_overview:
  show_all_posts: true

social_links:
  github: https://github.com/jinan36
  weibo: https://weibo.com/210127007
  bilibili: https://space.bilibili.com/19220486
  zhihu: https://www.zhihu.com/people/zhuang-ji-nan-83
  rss: /atom.xml

copyright:
  start_year: 2022
  end_year:

rss:

google_analytics:
  enabled: true
  id: "G-LL017RHM9G"

highlight: kimbie

cdn:
  enable: true
  jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  clipboard: https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.7/clipboard.min.js
  font_awesome: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.2.0/css/all.min.css
  justified_gallery_css: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/css/justifiedGallery.min.css
  justified_gallery_js: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js

favicon:
  desktop:
    url: /favicon.svg
    gravatar: false
  android:
    url: /favicon.svg
    gravatar: false
  apple:
    url: /favicon.svg
    gravatar: false

logo:
  enable: false

giscus:
  enabled: true
  repo: jinan36/jinan36.github.io
  repo_id: R_kgDOH8cUBQ
  category: Announcements
  category_id: DIC_kwDOH8cUBc4CRQLU
  mapping: url
  strict: 1
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  theme: preferred_color_scheme
  lang: zh-CN
